version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    environment:
      PGUSER: postgres
      PGPASSWORD: dojot
      PGDATABASE: dojot
      PGHOST: db
      SESSION_SECRET: QPoRJjUtwCQe1exUX1CFbzGfAH8XjCUN
    depends_on:
      - db 
    ports:
      - "3000:3000"

  db:
    image: "postgres:11.2-alpine"
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile  
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dojot
      POSTGRES_DB: dojot

      